VGB-13
green-fox-academy/Vulpes-Gitinder-Backend pull request #4
Opened 2018-12-14 13:21 UTC by Jonathan-Bonnin

VGB-13: User Model is created

2018-12-14 13:50 UTC, adamgyulavari requested changes

2018-12-14 13:50 UTC, adamgyulavari commented on GiTinder.Tests/Models/UserTests.cs
> +            Assert.False(user == null);
@Jonathan-Bonnin `Assert.True(true)`

2018-12-14 13:50 UTC, adamgyulavari commented on GiTinder.Tests/Models/UserTests.cs
> +            Assert.False(user == null);
but we can remove this test

2018-12-17 14:52 UTC, Jonathan-Bonnin commented on GiTinder.Tests/Models/UserTests.cs
> +            Assert.False(user == null);
This test has been deleted :)

2018-12-20 14:24 UTC, adamgyulavari commented
@Jonathan-Bonnin resolve conflicts

2019-01-07 13:31 UTC, adamgyulavari approved these changes

2019-01-08 15:58 UTC, merged