VGB-15: Implement POST /login
green-fox-academy/Vulpes-Gitinder-Backend pull request #9
Opened 2019-01-07 14:38 UTC by Jonathan-Bonnin

2019-01-08 15:24 UTC, adamgyulavari requested changes

2019-01-08 15:24 UTC, adamgyulavari commented on GiTinder/Controllers/UsersController.cs
> +        }
@Jonathan-Bonnin remove unnecessery endpoints from controller

2019-01-08 15:24 UTC, adamgyulavari commented on GiTinder/Controllers/UsersController.cs
> +    [Route("api/[controller]")]
@Jonathan-Bonnin this is not needed here

2019-01-08 15:24 UTC, adamgyulavari commented on GiTinder/Controllers/UsersController.cs
> +        [HttpPost("/api/login")]
@Jonathan-Bonnin this should be `/login`

2019-01-08 15:24 UTC, adamgyulavari commented on GiTinder/Services/UserServices.cs
> +                }
@Jonathan-Bonnin you can use guid for this

2019-01-08 15:24 UTC, adamgyulavari commented on GiTinderTests/Models/UserTests.cs
> +﻿using System;
@Jonathan-Bonnin remove GiTinderTest project

2019-01-08 16:22 UTC, Jonathan-Bonnin commented
@adamgyulavari 

- removed unneeded endpoints
- token is created using Guid
- duplicated Test folder removed
- endpoint changed from "/api/login" to "/login"\
- merge conflicts resolved

2019-01-09 11:45 UTC, adamgyulavari approved these changes

2019-01-09 12:00 UTC, merged